version: "3.8"

services:
  ovh-sniper:
    build:
      context: .
      dockerfile: Dockerfile
    image: iniwex-ovh:latest
    container_name: ovh-sniper
    ports:
      - "20001:80"
    environment:
      - DEBUG=false
      - VITE_API_URL=/api
      - API_SECRET_KEY=akashi178..
      - ENABLE_API_KEY_AUTH=true
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/backend/data
      - ./logs:/app/backend/logs
      - ./cache:/app/backend/cache
    restart: unless-stopped
